#!/bin/bash
# Check for AI-generated content patterns in documentation files

echo "Checking for AI-generated content patterns..."

# AI content patterns to check for
PATTERNS=(
    "generated by"
    "ai-generated"
    "ai created"
    "created by artificial intelligence"
    "chatgpt"
    "claude"
    "copilot"
    "anthropic"
    "openai"
    "large language model"
    "llm"
    "ai assistant"
    "as an ai"
)

ERRORS=0

# Check all markdown files in the repo
for file in $(find . -name "*.md" -type f -not -path "./.git/*" -not -path "./node_modules/*" -not -path "./vendor/*"); do
    echo "Checking $file..."
    
    for pattern in "${PATTERNS[@]}"; do
        if grep -q -i "$pattern" "$file" 2>/dev/null; then
            echo "  ❌ Found potential AI-generated content pattern: \"$pattern\" in $file"
            grep -n -i "$pattern" "$file" 2>/dev/null
            ERRORS=$((ERRORS + 1))
        fi
    done
    
    # Check for overly structured/robotic language patterns
    ROBOTIC_PHRASES=(
        "in conclusion"
        "as previously mentioned"
        "it is important to note"
        "this document will"
        "the following section"
        "in this article"
        "we will discuss"
        "as we have seen"
        "in summary"
    )
    
    for phrase in "${ROBOTIC_PHRASES[@]}"; do
        if grep -q -i "$phrase" "$file" 2>/dev/null; then
            echo "  ⚠️  Found potentially robotic phrase: \"$phrase\" in $file"
            grep -n -i "$phrase" "$file" 2>/dev/null
        fi
    done
done

if [ $ERRORS -gt 0 ]; then
    echo ""
    echo "❌ Found $ERRORS potential AI-generated content patterns"
    echo "Please review the flagged content and make it sound more human-written."
    exit 1
else
    echo "✅ No AI-generated content patterns found!"
    exit 0
fi