#!/usr/bin/env bash
# Freeze the version a SearXNG checkout reports, at build time.
#
# The footer and /config show VERSION_STRING: the exact upstream commit this
# build is based on (commit date + hash, in upstream's own format) plus the RAMA
# release, so anyone can check the instance runs a current SearXNG. VERSION_TAG
# stays the bare upstream version because upstream sends it as the outgoing
# User-Agent ("SearXNG/<tag>") — a fork suffix there would single the instance
# out to every engine. Freezing also stops searx shelling out to git at import
# time (installed trees ship without .git).
#
# Every channel calls this: PKGBUILD, Dockerfile, install.sh. The RAMA release
# comes from the repo's VERSION file — bump it there, nowhere else.
#
# Usage: freeze-version.sh <searxng_checkout> <rama_repo_root>
set -euo pipefail

SXNG="${1:?searxng checkout dir required}"
RAMA="${2:?rama repo root required}"

rama_version="$(tr -d '[:space:]' < "$RAMA/VERSION")"
[ -n "$rama_version" ] || { echo "ERROR: $RAMA/VERSION is empty" >&2; exit 1; }

# mirrors upstream searx/version.py get_git_version(): Y.M.D with the leading
# zeros dropped, '+', short hash — e.g. 2026.10.2+19ffbcd30
upstream="$(git -C "$SXNG" show -s --date='format:%Y.%m.%d' --format='%cd+%h' | sed 's/\.0/./g')"
[ -n "$upstream" ] || { echo "ERROR: could not read upstream commit from $SXNG" >&2; exit 1; }

cat > "$SXNG/searx/version_frozen.py" <<EOF
# THIS FILE IS GENERATED BY scripts/freeze-version.sh
# DO NOT EDIT IT MANUALLY

VERSION_STRING = "${upstream} (RAMA ${rama_version})"
VERSION_TAG = "${upstream}"
DOCKER_TAG = "${upstream/+/-}"
GIT_URL = "https://github.com/Nomadcxx/searxng-RAMA"
GIT_BRANCH = "main"
EOF

echo "Frozen version: ${upstream} (RAMA ${rama_version})"
